name: "Promote latest release to APT Store"
on: workflow_call

jobs:
  update-apt-repo:
      name: Publish to Repo
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Get the release
        id: get_release
        uses: cardinalby/git-get-release-action@1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: v${{ needs.tag.outputs.version }}

      - name: Download release assets
        uses: dsaltares/fetch-gh-release-asset@0.0.8
        with:
          version: ${{ steps.get_release.outputs.id }}
          regex: true
          file: "homebridge.*\\.deb"
          target: "repo/"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install deb-s3
        run: |
          curl -sLO https://github.com/deb-s3/deb-s3/releases/download/0.11.3/deb-s3-0.11.3.gem
          sudo gem install deb-s3-0.11.3.gem

      - name: Update Repo
        run: |
          sudo chown -R $USER: repo/
          deb-s3 upload \
            --codename=${{ needs.release_type.outputs.release_type }} \
            --preserve-versions \
            --s3-region=us-west-2 \
            --bucket repo.homebridge.io \
            --access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --sign=${{ secrets.GPG_KEY_ID }} \
            repo/*.deb

    purge_cloudflare_cache:
      name: Clear Cache
      needs: update-apt-repo
      uses: ./.github/workflows/purge-cf-cache.yml
      secrets:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}

    github-releases-to-discord:
      name: Discord Webhooks
      needs: [tag,release_type,build,update-apt-repo,purge_cloudflare_cache]
      uses: homebridge/.github/.github/workflows/discord-webhooks.yml@latest
      with:
        title: "Homebridge APT Package Release"
        description: |
          Version `v${{ needs.tag.outputs.version }}`
        url: "https://github.com/homebridge/homebridge-apt-pkg/releases/tag/v${{ needs.tag.outputs.version }}"
      secrets:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL_LATEST }}
