name: "After update of package.json by dependabot - create a release and build APT package"

on:
  push:
    branches:
      - latest
    paths:
      - package.json

jobs:
  if_merged:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    if: ${{ github.event.head_commit.author.username == 'NorthernMan54' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.processed_version }}
    steps:
    - run: |
        echo The PR was merged

    - uses: release-drafter/release-drafter@v6
      id: drafter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove V from the version tag
      id: extract_version
      run: |
        echo "The tag name is: ${{ steps.drafter.outputs.tag_name }}"
        PROCESSED_VERSION=$(echo "${{ steps.drafter.outputs.tag_name }}" | sed 's/^v//') # Remove 'v'
        echo "::set-output name=processed_version::$PROCESSED_VERSION"

  
  build_package_and_store:
    needs: if_merged
    uses: ./.github/workflows/_build_package_and_store.yml
    with:
      version: ${{ needs.if_merged.outputs.version }}

  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"