name: "Stage 2 - Pre-Release Validation Workflow"

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "The tag of the release to validate."
        required: true
        type: string
  release:
    types: [published, prereleased]

jobs:
  determine_release_tag:
    name: Determine Release Tag
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_release_tag.outputs.release_tag }}
    steps:
      - name: Set Release Tag
        id: set_release_tag
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "release_tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "release_tag=${{ inputs.release_tag }}" >> "$GITHUB_OUTPUT"
          fi

  count_prerelease_assets:
    name: Download Latest Pre-Release Assets
    runs-on: ubuntu-latest
    needs: determine_release_tag
    steps:
      - name: Download prerelease assets
        id: download_assets
        uses: robinraju/release-downloader@v1.11
        with:
          tag: ${{ needs.determine_release_tag.outputs.release_tag }}
          fileName: 'homebridge*.deb'
      
      - name: List the downloaded files
        run: ls -l

      - name: Check the number of downloaded files
        id: check_file_count
        run: |
          FILE_COUNT=$(ls -1 | wc -l)
          echo "Number of files downloaded: $FILE_COUNT"
          if [ "$FILE_COUNT" -ne 3 ]; then
            echo "::error::Expected 3 files, but found $FILE_COUNT"
            exit 1
          fi

  validate_prerelease_x86_package:
    needs: [determine_release_tag, count_prerelease_assets]
    name: Download, Install, and Validate Homebridge Package
    runs-on: ubuntu-latest
    steps:
      - name: Download release asset
        id: download_release
        uses: robinraju/release-downloader@v1.11
        with:
          tag: ${{ needs.determine_release_tag.outputs.release_tag }}
          fileName: 'homebridge_v1.3.10_amd64.deb'
      
      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -l

      - name: Install the downloaded package
        run: |
          sudo dpkg -i homebridge_v1.3.10_amd64.deb || sudo apt-get install -f -y
          sleep 30

      - name: Validate Homebridge Service
        run: |
          sudo hb-service view
          sudo hb-service status

  print_context:
    needs: determine_release_tag
    runs-on: ubuntu-latest
    steps:
      - name: Dump Inputs context
        env:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: echo "$INPUTS_CONTEXT"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"
          echo "The id of this action is: $GITHUB_ACTION"
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
