name: "Test Stage 1 - Create a pre-release and build APT package"

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Release Level'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

#  push:
#    branches:
#      - latest
#    paths:
#      - package.json

jobs:
  merge_inputs:
    # allows for both the workflow_dispatch and push events to trigger this job
    runs-on: ubuntu-latest
    outputs: 
      username: ${{ steps.merge_username.outputs.username }}
      increment: ${{ steps.merge_increment.outputs.increment }}
    steps:
      - name: Merge Username
        id: merge_username
        run: |
          if [ "${{ github.event.head_commit.author.username }}" ]; then
            USERNAME=${{ github.event.head_commit.author.username }}
          else
            USERNAME='NorthernMan54'
          fi
          echo "Using USERNAME: $USERNAME"
          echo "username=$USERNAME" >> "$GITHUB_OUTPUT"

      - name: Merge Username
        id: merge_increment
        run: |
          if [ "${{ inputs.increment }}" ]; then
            INCREMENT=${{ inputs.increment }}
          else
            INCREMENT=patch
          fi
          echo "Using INCREMENT: $INCREMENT"
          echo "increment=$INCREMENT" >> "$GITHUB_OUTPUT"

  create_draft_prerelease:
    # Only run this job if the username is NorthernMan54
    needs: merge_inputs
    if: ${{ needs.merge_inputs.outputs.username == 'NorthernMan54' }}
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release_version.outputs.version }}  # Without a V
      v-version: ${{ steps.release_version.outputs.v-version }}  # With a V
    #  release_id: ${{ steps.create_release.outputs.id }}
    #  release_upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_type: 'stable'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: release_version
        with:
          scheme: semver
          increment: ${{ needs.merge_inputs.outputs.increment }}

      - name: Dump Inputs context
        env:
          INPUTS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$INPUTS_CONTEXT"