on:
  workflow_dispatch:
  release:
    types: [prereleased]

jobs:
  download_prerelease_assets:
    name: Download Latest Pre-Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Download prerelease assets
        id: download_assets
        uses: robinraju/release-downloader@v1.11
        with:
          latest: true
          preRelease: true
          fileName: 'homebridge*.deb'
      
      - name: List the downloaded files
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"

      - name: List downloaded files
        run: ls -l

      - name: Check the number of downloaded files
        id: check_file_count
        run: |
          FILE_COUNT=$(ls -1 | wc -l)
          echo "Number of files downloaded: $FILE_COUNT"
          if [ "$FILE_COUNT" -ne 3 ]; then
            echo "::error::Expected 3 files, but found $FILE_COUNT"
            exit 1
          fi
